title: MM
header-img: img/home-bg.png
email: marusak.matej@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Matej Marusak
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marusak.github.io" # the base hostname & protocol for your site
github_username: marusak

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
